### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by MFDGaming** [AyrA/WADex#1]
How can i install wadex

**Comment by AyrA** [comment]
Go to [the releases page](https://github.com/AyrA/WADex/releases) and download `WADex.exe`

This is a command line utility. Open a command prompt and navigate to the directory where you put the executable, then run `WADex.exe` for Help or check [the readme file](https://github.com/AyrA/WADex/blob/master/README.md)

**Comment by AyrA** [comment]
I want to add here that you are maybe a linux user according to the repositories in your github account. To run this on a Linux machine you need the Mono framework. I don't think I use any windows specific functions so it should run "as-is"

**Comment by MFDGaming** [comment]
I use both windows and Linux. My main os is windows 8.1

**Comment by MFDGaming** [comment]
Thanks for the link

**Comment by rawr51919** [comment]
This isn't really an issue, so it might as well be closed now.
